name: syncify_final
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  google_nav_bar: ^5.0.6
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  audioplayers: ^6.1.0
  youtube_explode_dart: ^1.10.4
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.1
  image_picker: ^0.8.7+3
  permission_handler: ^10.3.0
  firebase_app_check: ^0.3.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/song_dp1.jpg
    - assets/images/song_dp2.jpg
    - assets/images/default_dp.jpg

# App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


# Banner layout
flutter_native_splash:
  android: true
  ios: true
  color: "#42a5f5"
  android_12:
    image: assets/banner/banner_logo.png
    color: "#FFFFFF"
    color_dark: "#000000"
